### ISSUE TITLE
ElementNodeReference.remove method

### ISSUE THREAD

**Issue by ppokyd** [Datamart/Glize#3]
To reduce size after compilation.
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove

**Comment by vpodk** [comment]
See [`dom.removeNode`](https://github.com/Datamart/Glize/blob/master/src/dom/__ns__.js#L254).

**Comment by vpodk** [comment]
Updated documentation: [dom.removeNode](http://datamart.github.io/Glize/docs/dom.html#.removeNode)
